export const ACTION_LOGIN_PENDING = "ACTION_LOGIN_PENDING";
export const ACTION_LOGIN_SUCCESS = "ACTION_LOGIN_SUCESS";
export const ACTION_LOGIN_FAIL = "ACTION_LOGIN_FAIL";
export const ACTION_LOGOUT = "ACTION_LOGOUT";

export const ACTION_LOAD_TODO = "ACTION_LOAD_TODO";
export const ACTION_ADD_TODO = "ACTION_ADD_TODO";
export const ACTION_SEARCH_TODO = "ACTION_SEARCH_TODO";
export const ACTION_UPDATE_TODO = "ACTION_UPDATE_TODO";

export const ACTION_TOGGLE_FILTER = "ACTION_TOGGLE_FILTER";

export const ACTION_TOGGLE_TAG = "ACTION_TOGGLE_TAG";
export const ACTION_ADD_TAG = "ACTION_ADD_TAG";

export const ACTION_RESET_STATE = "ACTION_RESET_STATE";
