export const ACTION_LOGIN_PENDING = 'ACTION_LOGIN_PENDING';
export const ACTION_LOGIN_SUCCESS = 'ACTION_LOGIN_SUCESS';
export const ACTION_LOGIN_FAIL = 'ACTION_LOGIN_FAIL';
export const ACTION_LOGOUT = 'ACTION_LOGOUT';

export const ACTION_ADD_TODO = 'ACTION_ADD_TODO';

export const ACTION_TOGGLE_FILTER = 'ACTION_TOGGLE_FILTER';

export const ACTION_TOGGLE_TAG = 'ACTION_TOGGLE_TAG';