export const ACTION_LOGIN_PENDING = 'ACTION_LOGIN_PENDING';
export const ACTION_LOGIN_SUCCESS = 'ACTION_LOGIN_SUCESS';
export const ACTION_LOGIN_FAIL = 'ACTION_LOGIN_FAIL';
export const ACTION_LOGOUT = 'ACTION_LOGOUT';